### ISSUE TITLE
Get UID And Serial Number of the NFC Tag iOS

### ISSUE THREAD

**Issue by ghost** [FabianGroeger96/NFC-Background-reading#1]
I'm developing an application in which I want to get the NFC serial number and Identifier of a NFC tag. When I press a button, I want the application to find the UID and serial number of the NFC card. The only problem is that I have no idea how to get the UID and and serial number if that's possible on iOS. I m trying to get NFC identifier but i don't know how to get serial number of NFC Tag. 

Code:- 

    class ScanNFCTag: NFCTagReaderSessionDelegate {

    import CoreNFC

    var session: NFCTagReaderSession?

    func scanNFCTag(sender: UIButton!) {
         self.session = NFCTagReaderSession(pollingOption: .iso14443, delegate: self)
         self.session?.alertMessage = "Hold Your Phone Near the NFC Tag"
         self.session?.begin()
    }

    func tagReaderSessionDidBecomeActive(_ session: NFCTagReaderSession) {
        print("Session Begin!")
    }
    
    func tagReaderSession(_ session: NFCTagReaderSession, didInvalidateWithError error: Error) {
        print(error.localizedDescription)
    }
    
    func tagReaderSession(_ session: NFCTagReaderSession, didDetect tags: [NFCTag]) {
        if tags.count > 1{
            session.alertMessage = "More Than One Tag Detected, Please try again"
            session.invalidate()
        }
        
        let tag = tags.first!
        session.connect(to: tag) { (error) in
            if nil != error{
                session.invalidate(errorMessage: error?.localizedDescription ?? "")
            }
            if case let .miFare(sTag) = tag{
                let UID = sTag.identifier.map{ String(format:"%.2hhx", $0)}.joined()
                session.alertMessage = "Successfully linked tag to location"
                session.invalidate()
                DispatchQueue.main.async {
                    print("NFC Identifer = ", "\(UID)")
                   }
               }
           }
       }
    }

So, Here is the my code please let me know if i m doing wrong please correct me. Can someone please explain to me how to get serial number and UID of NFC tag,

Any help would be greatly appreciated.

Thanks in advance.

**Comment by crzdg** [comment]
We tried to use the UID to identify NFC Tags with Android and iOS as well. Unfortanently Apple iOS did not support UID reading from NFC tags back then.

https://developer.apple.com/forums/thread/89287

I don't know what the status of this is at the moment, but as far I can remember Apple does not care about UID as they are compromised anyway. 

We ended up writing our own Identifier field on the NFC tags to be able to uniquely identify tags.

**Comment by ghost** [comment]
Ok Is there any other option to get the serial number of NFC tag?
@crzdg

**Comment by crzdg** [comment]
@shamdass Sorry for the late response. We didn't research this extensively. As said, as far I'm concerned it is not possible to get the serial number of an NFC tag reliable enough with the iOS library. But this was almost two years so it might have changed. You might find more precise and update information nowadays. Search for "CoreNFS" in combination with "Tag ID", etc...

I repeat, we ended up writing an NFC tag field called where we set our own internally valid ID for the tag. This way we were able to identify tags.

**Comment by ghost** [comment]
@crzdg Okay, I understand your point, Thank you so much your reply

**Comment by zarzonis** [comment]
HI @crzdg Sorry for mentioning you after all these months but the approach you said you followed seems interesting and I would really appreciate your help. In your solution did you took into consideration NFC cloning or it didn't matter for your usage? I want to write a few NFC Tags with a custom ID just like you did but I also want to prevent someone from reading the NFC data using an app and just write the same data to a different NFC Tag. In that case I'll have two different NFC Tags with the same data.

**Comment by SafwanSiddique** [comment]
You probably don't need this anymore but It might someone else out :)
What you did was correct for the uuid. You can further format the UUID to serial number as the serial number is derived from the UUID. Correct me if I am wrong although I matched the serial number I was getting to the one NFC Tool shows. I use the following code to further structure the uuid correctly into the serial number format. 

  



   let uid = stag.identifier.map{ String(format: "%.2hhx", $0) }.joined()
   print(uid) 
   serial_NFC = uid
serial_NFC = uid.capitalized
serial_NFC.insert(":", at: serial_NFC.index(serial_NFC.startIndex, offsetBy: 2))
serial_NFC.insert(":", at: serial_NFC.index(serial_NFC.startIndex, offsetBy: 2+3))
serial_NFC.insert(":", at: serial_NFC.index(serial_NFC.startIndex, offsetBy: 5+3))
serial_NFC.insert(":", at: serial_NFC.index(serial_NFC.startIndex, offsetBy: 8+3))
serial_NFC.insert(":", at: serial_NFC.index(serial_NFC.startIndex, offsetBy: 11+3))
serial_NFC.insert(":", at: serial_NFC.index(serial_NFC.startIndex, offsetBy: 14+3))
serial_NFC = serial_NFC.capitalized
print(serial_NFC)
